services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString